### PR TITLE
Include options parameter for child_process.spawn function call

### PR DESCRIPTION
**Pull request by renanwilliam**
When is required setup environments variables it can be done in the last parameter of child_process.spawn function. This pull request include support for this parameter.

### CODE REVIEW

**Comment by dani8art** [comment]
That is good, but I don't know, why do you need this feature? could you give me any use case?

Anyway, if it was necessary, it would be great to have this feature also in the others functions.

**Comment by renanwilliam** [comment]
Hi,

I'm using it because I need to setup ENV values for my containers and it need to be dynamic (can't just use .env files). I think that is necessary in docker-compose up only but we can create this interface for all methods. I will try do it tomorrow and update the PR.

**Comment by renanwilliam** [comment]
Included for all methods

**Comment by dani8art** [comment]
Hi @renanwilliam,
Could we name the parameter `processOpt`? so this name is more intuitive. what do you think?

**Comment by renanwilliam** [comment]
Sure, added

**Comment by dani8art** [comment]
Hi @renanwilliam,
I write you to say that finally, I have not merged your new feature to the master branch. I have been read about child_process and if you want to pass environment variables to it, the best way is to do through the global variable `process.env` as follow:

```
var dcManager = require('docker-composer-manager');
var file = __dirname + '/docker-compose.yaml';

process.env.MONGO_VERSION = '3.0.15';

dcManager.dockerComposeUp(file).then(() => {
    return dcManager.dockerExec('withenvironment_mongo_1', ['mongo', '--version']);
}).then((out) => {
    return Promise.resolve(expect(out.indexOf('3.0.15')).to.not.be.equal(-1));
}).then(() => {
    return dcManager.dockerComposeDown(file);
}).then(() => done()).catch(err => done(err));
```

```
version: '3'
services:
  mongo:
    image: mongo:${MONGO_VERSION}
```
However, I save your code in the branch `feature/process-opt`, maybe in the future, it would be necessary.

Thank you very much, I appreciate your opinion and I hope you continue sending me all your improvements.

**Comment by renanwilliam** [comment]
Hi @dani8art,

It’s another way but my application start multiples containers in an unpredictable order and numbers, according with demand and each container have your own ENV data (absolutely don't have any data shared). I believe that this approach (send the env in parameter) will work better for me. I will keep my fork because I will use it in a productive application but I will try send some new updates.

Thank you.

**Pull request merged**
